sudo: required
dist: trusty
language: generic
cache:
  timeout: 660
  pip: true
  custom_install: true
  directories:
    - build/llvm
    - third_party/llvm
os:
 - linux
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qqy libxml2-dev git cmake libprotoc-dev libprotobuf-dev libprotobuf-dev protobuf-compiler python2.7 python-pip llvm-3.8 clang-3.8 realpath gcc-multilib
 - sudo pip install 'protobuf==2.6.1'
install: true
script:
 - ./bootstrap.sh
 - python tests/integration_test.py
notifications:
  slack:
    secure: fcMGmYpC9Ce34qq+hQSVj3Xe6OE4xol3k8rED74rRvllKrzYG9Dj6FdYgejQiu13znsVv4P08aSvX9A+/mTadTAVf+3yH/XJ12i+NX7M45jfQ0iHpoiM9+Tre/oc0IdjC2JWoFpsy5Ukf/+f6GUdQEq/6xlI4lMdL2PwXkNJTaUhYNn2avg0qa/nB7NmoiNzq0pT0Miy3MlkwZy//yjrH4bPJVXVJVgL7Q8SDhlHjlQD2GRCBKWjrCQBcDce8gxDuDMkS1y0SD5HU4mS5hOjS9hZ/JLVBLdt0Z5DPtnUJvJHXA6JPEJInc0a5qMsG43y4TfgyMGWLAZSOsxQcY8R7C67sRXhmBZ++X1808Wl+wxuIR0vXkRtN2GHuFbr2NlHMRZgr8TelszBn3SosudGeLZyFS493UudE4acSVVvBAlwoSk0TD5wWKN4RnrFcSIEBRS9imcFK/KSIXTUFQorrkHh102LylgnR4kscVorPhYSaL1TqHUp3icBREHcMRI041cae4uItigVv5t1UVRyz7sNIz51UoezHAqVdGL5B3xozJ+ng2azwvnRMFkdE0EoHZKZrTiTR46V8nabc7g1wqipQ7z7xR/zzkZMtBNRjMtsvbBsVFiaLHHrVdRpkF4rlspuKpc1s9KW1b+AEyuD+qJNZ57kSI5Gz26WqOB8zNQ=
